# 1.
name: Test & Build

# 2.
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

# 3.
jobs:
  main:
    runs-on: macos-latest

    # 4.
    steps:
      # 5.
      - name: Clone repository
        uses: actions/checkout@v4

      # 6.
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18.x'

      # 7.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 8.
      - name: Install FVM
        run: |
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      # 9.
      - name: Setup Flutter with FVM
        run: |
          fvm install
          fvm flutter --version

      # 10.
      - name: Get Flutter packages
        run: |
          fvm flutter pub get

      # 11.
      - name: Run build_runner
        run: |
          fvm flutter pub run build_runner build --delete-conflicting-outputs

      # 12.
      - name: Check for lints
        run: |
          fvm flutter analyze

      # 13.
      - name: Run all tests
        run: |
          fvm flutter test

      # 14.
      - name: Build APK
        run: |
          fvm flutter build apk

      # 15.
      - name: Flutter build ipa
        run: |
          fvm flutter build ipa --no-codesign

      # 16.
      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      # 17.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios_build.tar.gz
